language: c

matrix:
  include:
  - os: linux
    dist: xenial
    sudo: required
  - os: linux
    dist: jessie
    sudo: required
  - os: osx
    osx_image: xcode8.3

compiler: gcc

# The EDU plan doesn't support sudo :(

#before_install:
#   - sudo apt-get update -qq
#   - apt-get install -y cppcheck

script:
#   - cppcheck --enable=warning,style,performance,portability,missingInclude --std=c89 *.c -q
  - cd libft && make && cd ..
  - make

after_success:
  - ./ft_inspect_file libft/
  - ./ft_inspect_file main.c
